---
- name: "Reading Address Book and Policies"
  address_book:
    host_file={{host_file}}
  changed_when: False
  when: commit_changes | match('0')

- name: "Building Address Book and Policies"
  template: src={{os}}/firewall.j2 dest=../{{baseconfdir.path}}/firewall.out
  changed_when: False
  when: commit_changes | match('0')

