---
- hosts: frontend
  remote_user: napalm

  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=installed
      sudo: yes
      notify:
        - start nginx

  handlers:
    - name: start nginx
      sudo: yes
      service: name=nginx state=started

- hosts: backend
  remote_user: napalm

  tasks:
    - name: Install MySQL
      apt: pkg={{ item }} state=installed
      sudo: yes
      with_items:
        - python-mysqldb
        - mysql-server
      notify:
        - start mysql

  handlers:
    - name: start mysql
      sudo: yes
      service: name=mysql state=started
