---
- name: Build site configuration
  hosts: all
  connection: local
  gather_facts: no
  vars:

  pre_tasks:
    - name: Remove old config
      file: path=compiled/{{ inventory_hostname }}/ state=absent
      register: baseconfdir
      changed_when: False
    - name: Create empty
      file: path={{baseconfdir.path}} state=directory
      changed_when: False

- include : tasks/def_roles.yml
- include : tasks/assemble_push_conf.yml
