---
- name: Getting facts with napalm
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: napalm_get_facts
      napalm_get_facts:
        hostname={{ inventory_hostname }}
        username=demo
        dev_os={{os}}
        password=Lab123
      when: commit_changes | match('0')

      tags:
        - base
