---
- name: "Building IP Fabric"
  template: src={{os}}/svcinterconnect.j2 dest=../{{baseconfdir.path}}/svcinterconnect.out
  changed_when: False
  when: commit_changes | match('0')
  tags:
    - netserv
