---
- name: "Building configuration from CORE role"
  template: src={{os}}/core.j2 dest=../{{baseconfdir.path}}/01_core.out
  changed_when: False
  when: commit_changes | match('0')
  tags:
     - base
